version: '3'

services:
  todo-app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - redis-server

  redis-server:
    image: redis
    container_name: cache
    expose:
      - 6379
